MOV AH, 00H ;SERVICIO PARA ESTABLECER EL MODO DE VIDEO
MOV AL, 02H ;= Modo de video 80X25
INT 10H

;LIMPIAR PANTALLA
MOV AH, 06H
MOV AL, 00H ; 0 = BORRA
MOV BH, 003H ; = Atributo de las lineas en blanco COLOR ;FONDO NEGRO COLOR AZUL
;1e. NIBLE COLOR DEL BACKGROUND
;2do. NIBLE COLOR DEL TEXTO
MOV CX, 00H    ;POSICION INICIAL A BORRAR
MOV DH, 24     ;POSICION FINAL A BORRAR
MOV DL, 79
INT 10H   

   
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX MARGEN ASTERISCOS


MOV CX, 23 ;INICIO LOOP
BARRAIZQ:  ;BARRA VERTICAL IZQUIERDA
    ;COLOCAR EL CURSOR EN EL EXTREMO INF IZQ DE LA PANTALLA
    MOV AH, 02H       ; SERVICIO DE POSICIONAR EL CURSOR
    MOV BH, 0         ; PAGINA ACTUAL
    MOV DH, IZQUIERDA ; FILA
    MOV DL, 0         ; COLUMNA 
    INT 10H
    
    MOV AH, 02H       ; IMPRIMIR UN CARACTER EN PANTALLA
    MOV DL, 02Ah
    INT 21H
    
    ADD IZQUIERDA, 1
LOOP BARRAIZQ

  
       
MOV CX, 23 ;INICIO LOOP
BARRADER:  ; BARRA VERTICAL DERECHA
    ;COLOCAR EL CURSOR EN EL EXTREMO DER SUPERIOR DE LA PANTALLA
    MOV AH, 02H     ; SERVICIO DE POSICIONAR EL CURSOR
    MOV BH, 0       ; PAGINA ACTUAL
    MOV DH, DERECHA ; FILA
    MOV DL, 79      ; COLUMNA
    INT 10H
    
    MOV AH, 02H     ; IMPRIMIR UN CARACTER EN PANTALLA
    MOV DL, 02Ah
    INT 21H  
    
    ADD DERECHA, 1
LOOP BARRADER



;BARRA HORIZONTAL SUPERIOR
MOV AH, 02H       ; SERVICIO DE POSICIONAR EL CURSOR
MOV BH, 0         ; PAGINA ACTUAL
MOV DH, 0         ; FILA
MOV DL, 0         ; COLUMNA
INT 10H

MOV AH, 09        ; SERV PARA IMPRIMIR UNA CADENA
MOV DX, OFFSET MH ; COLOCO LA DIRECCIÓN DE LA CADENA A IMPRIMIR
INT 21H



;BARRA HORIZONTAL INFERIOR
MOV AH, 02H       ; SERVICIO DE POSICIONAR EL CURSOR
MOV BH, 0         ; PAGINA ACTUAL
MOV DH, 23        ; FILA
MOV DL, 0         ; COLUMNA
INT 10H



MOV AH, 09        ; SERV PARA IMPRIMIR UNA CADENA
MOV DX, OFFSET MH ; COLOCO LA DIRECCIÓN DE LA CADENA A IMPRIMIR
INT 21H

 
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX TEXTO 


;BIENVENIDOS  
MOV BH, 0      ; PAGINA ACTUAL
MOV AH,19 
MOV CX,11      ;LONGITUD CADENA
MOV DH,4       ;FILA
MOV DL,32      ;COLUMNA 
LEA BP,BIENV   ;NOMBRE CADENA
MOV AL,0       ;MODO
MOV BL, 1H     ;COLOR
INT 10H 

      
;LETRERO NIP  
MOV BH, 0      ; PAGINA ACTUAL
MOV AH,19 
MOV CX,12      ;LONGITUD CADENA
MOV DH,7       ;FILA
MOV DL,32      ;COLUMNA 
LEA BP,NIP     ;NOMBRE CADENA
MOV AL,0       ;MODO
MOV BL, 5H     ;COLOR
INT 10H      
      
           
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ENTRADA NIP 


;ENTRADA PRIMER DIGITO
MOV AH, 02H    ; SERVICIO DE POSICIONAR EL CURSOR
MOV BH, 0      ; PAGINA ACTUAL
MOV DH, 10     ; FILA
MOV DL, 35     ; COLUMNA
INT 10H
;LECTURA SIN ECO #1
MOV AH, 07H
INT 21H        ; DEJA EN AL EL CODIGO ASCII
MOV NIP1, AL   ; GUARDA DIGITO LEIDO 
;IMPRIMIR ASTERISCO
MOV AH, 9    
MOV AL, 02AH   ; CARACTER
MOV CX, 1      ; LONGITUD CADENA 
MOV BH, 0      ; PAGINA ACTUAL 
MOV BL, 2H     ; COLOR
INT 10H 

   
   
;ENTRADA SEGUNDO DIGITO
MOV AH, 02H    ; SERVICIO DE POSICIONAR EL CURSOR
MOV BH, 0      ; PAGINA ACTUAL
MOV DH, 10     ; FILA
MOV DL, 36     ; COLUMNA
INT 10H
;LECTURA SIN ECO #2
MOV AH, 07H
INT 21H        ; DEJA EN AL EL CODIGO ASCII
MOV NIP2, AL   ; GUARDA DIGITO LEIDO 
;IMPRIMIR ASTERISCO
MOV AH, 9    
MOV AL, 02AH   ; CARACTER
MOV CX, 1      ; LONGITUD CADENA 
MOV BH, 0      ; PAGINA ACTUAL 
MOV BL, 2H     ; COLOR
INT 10H 



;ENTRADA TERCER DIGITO 
MOV AH, 02H    ; SERVICIO DE POSICIONAR EL CURSOR
MOV BH, 0      ; PAGINA ACTUAL
MOV DH, 10     ; FILA
MOV DL, 37     ; COLUMNA
INT 10H
;LECTURA SIN ECO #3
MOV AH, 07H
INT 21H        ; DEJA EN AL EL CODIGO ASCII
MOV NIP3, AL   ; GUARDA DIGITO LEIDO 
;IMPRIMIR ASTERISCO
MOV AH, 9    
MOV AL, 02AH   ; CARACTER
MOV CX, 1      ; LONGITUD CADENA 
MOV BH, 0      ; PAGINA ACTUAL 
MOV BL, 2H     ; COLOR
INT 10H 



;ENTRADA CUARTO DIGITO
MOV AH, 02H    ; SERVICIO DE POSICIONAR EL CURSOR
MOV BH, 0      ; PAGINA ACTUAL
MOV DH, 10     ; FILA
MOV DL, 38     ; COLUMNA
INT 10H    
;LECTURA SIN ECO #4
MOV AH, 07H
INT 21H        ; DEJA EN AL EL CODIGO ASCII
MOV NIP4, AL   ; GUARDA DIGITO LEIDO 
;IMPRIMIR ASTERISCO
MOV AH, 9    
MOV AL, 02AH   ; CARACTER
MOV CX, 1      ; LONGITUD CADENA 
MOV BH, 0      ; PAGINA ACTUAL 
MOV BL, 2H     ; COLOR
INT 10H 



;VALORACION DE NIP
MOV AL, CLAVE[0]
CMP AL, NIP1     ;SI(CLAVE[0] == NIP1) 
JNE DIFERENTES 


MOV AL, CLAVE[1]
CMP AL, NIP2     ;SI(CLAVE[1] == NIP2)
JNE DIFERENTES


MOV AL, CLAVE[2]
CMP AL, NIP3     ;SI(CLAVE[2] == NIP3) 
JNE DIFERENTES


MOV AL, CLAVE[3]
CMP AL, NIP4     ;SI(CLAVE[3] == NIP4) 
JNE DIFERENTES

;CORRECTO    
ADD AUX,1        
CMP AUX,01H
JE EXITO        
        
      
      
DIFERENTES:        
    ;NO SON IGUALES  CLAVE != NIP1  
    MOV BH, 0     ; PAGINA ACTUAL
    MOV AH,19 
    MOV CX,20     ; LONGITUD CADENA
    MOV DH,13     ; FILA
    MOV DL,28     ; COLUMNA 
    LEA BP,MAL    ; NOMBRE CADENA
    MOV AL,0      ; MODO
    MOV BL, 4H    ; COLOR
    INT 10H
    JMP FIN  
    
    
   
EXITO:
    ;IGUALES  
    MOV BH, 0     ; PAGINA ACTUAL
    MOV AH,19 
    MOV CX,18     ; LONGITUD CADENA
    MOV DH,13     ; FILA
    MOV DL,29     ; COLUMNA 
    LEA BP,BIEN   ; NOMBRE CADENA
    MOV AL,0      ; MODO
    MOV BL, 2H    ; COLOR
    INT 10H
    JMP FIN 
    
    
    
;FIN DEL PROGRAMA    
FIN:
    INT 20H 
    
    

MH DB '********************************************************************************$'
IZQUIERDA DB 1
DERECHA DB 1
AUX DB 0

NIP DB 'DAME TU NIP:$' 
BIENV DB 'BIENVENIDOS$'   
CLAVE DB "1234$"

BIEN DB 'EL NIP ES CORRECTO$'
MAL  DB 'EL NIP ES INCORRECTO$'

NIP1 DB 00H
NIP2 DB 00H
NIP3 DB 00H
NIP4 DB 00H